name: Build and Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install and build
        run: |
          rustup target add wasm32-unknown-unknown
          cargo install --locked trunk
          trunk build --release

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folter: dist
